spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/ templates/
    suffix: .html
    enabled: true
  application:
    name: board_study
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/board_study
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: false
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-board-study
jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        hibernate:
          "[format_sql]": "true"
          "[hbm2ddl.auto]": "update"
          "[implicit_naming_strategy]": "org.spring.framework.boot.jpa.hibernate.springImplicitNamingStrategy"
          #"[physical_naming_strategy]": org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        open-in-view: false
        show-sql: true


logging:
    level:
      root: INFO

server:
    port: ${myapp.port:8888}